apiVersion: 0.3.0
environments:
  dev:
    destination:
      namespace: kubeflow
      server: https://kubernetes.default.svc
    k8sVersion: v1.11.5
    path: dev
kind: ksonnet.io/app
libraries:
  kubeflow/argo:
    name: argo
    registry: kubeflow
    version: ""
  kubeflow/common:
    name: common
    registry: kubeflow
    version: ""
  kubeflow/jupyter:
    name: jupyter
    registry: kubeflow
    version: ""
  kubeflow/katib:
    name: katib
    registry: kubeflow
    version: ""
  kubeflow/metacontroller:
    name: metacontroller
    registry: kubeflow
    version: ""
  kubeflow/profiles:
    name: profiles
    registry: kubeflow
    version: ""
name: kubeflow
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: fs
    uri: /Users/hjarraya/IdeaProjects/equinor/kubeflow_src/kubeflow
  seldon-core:
    protocol: fs
    uri: ../../seldon-core/seldon-core
version: 0.0.1
